# %%
import pandas as pd
from mleco.data import load_dataset

# %load_ext autoreload
# %autoreload 2
# %% [markdown]
## Data Analysis
# We revisit LaLonde (1986)’s dataset, where the treatment is job training and the ouctomes are income and employment status after training. This dataset was first built to evaluate the impact of the National Supported Work (NSW) program. The NSW is a transitional, subsidized work experience program targeted towards people with longstanding employment problems. Here, the quantity of interest is the ATET, defined as the impact of the participation in the pro- gram on 1978 yearly earnings in dollars. This dataset combines a randomized study based on the National Supported Work program with observational data to form a larger dataset (Smith & Todd, 2005). The treated group comprises people who were randomly assigned to this program from the population at risk (n1 = 185). Two control groups are available. The first one is experimental: it is directly comparable to the treated group as it has been generated by a random control trial (sample size n0 = 260). The second one comes from the Panel Study of Income Dynamics (PSID) (sample size n0 = 2490). The presence of the experimental sample allows to obtain a benchmark for the ATET obtained with observational data.
# %%
data = load_dataset("lalonde", description=True)

# %%
data.head()
