# %%
from IPython.extensions.autoreload import AutoreloadMagics
import pandas as pd
from mleco.data import load_dataset
from mleco.data_acquisition import build_lalonde

%load_ext autoreload
%autoreload 2
# %%
desctiption, data = load_dataset("lalonde", description=True)
data
# %% [markdown]
## Data Analysis

# We revisit LaLonde (1986)’s dataset using the exercise in Bléhaut et al. (2020). This dataset was first built to evaluate the impact of the National Supported Work (NSW) program. The NSW is a transitional, subsidized work experience program targeted towards people with longstanding employment problems: ex-offenders, former drug addicts,women who were long-term recipients of welfare benefits and school dropouts. Here, the quantity of interest is the ATET, defined as the impact of the participation in the pro- gram on 1978 yearly earnings in dollars. The treated group comprises people who wererandomly assigned to this program from the population at risk (n1 = 185). Two control groups are available. The first one is experimental: it is directly comparable to the treated group as it has been generated by a random control trial (sample size n0 = 260). The second one comes from the Panel Study of Income Dynamics (PSID) (sample size n0 = 2490). The presence of the experimental sample allows to obtain a benchmark for the ATET obtained with observational data.
# %%
file = (
    "https://raw.githubusercontent.com/CausalAIBook/"
    "MetricsMLNotebooks/main/data/wage2015_subsample_inference.csv"
)
df = pd.read_csv(file)
# %%
df.head()
