name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # specify your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.8.3
          poetry install --no-interaction --without main --with documentation

      - name: Build the Sphinx documentation
        run: |
          make docs-html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html